texto_cifrado='QDIXZIORDGGZHQVIBJBCAJDPHKDIOJMCJGVIYZNIVNXDYJZHYZHVMJYZXJINDYZMVYJPHYJNVMODNOVNHVDNDIAGPZIOZNYJNPGODHJNOZHKJNZHWJMVNZPMZXJICZXDHZIOJOZICVNZYVYJVKZIVNYZKJDNYZNPVHJMOZZILPVIOJQDQJQZIYZPVKZIVNPHLPVYMJJQDICZYJQZMHZGCJQVIBJBCIPIXVDHVBDIJPVAVHVLPZQDMDVVOZMZMVADGCJYZOCZJYJMPNQVIBJBCZXJMIZGDVPHVHPGCZMXJHOZIYZIXDVNVMODNODXVNODICVLPVOMJDMHVJNHVDNIJQJNHVNAJDXJHOCZJNZBPIYJADGCJYJXVNVGLPZQVIBJCZNOVWZGZXZPPHVAJMOZMZGVXVJHVMXVYVKJMXVMOVNOMJXVYVNZIOMZJNYJDNXJHVNVPYZHZIOVGYZWDGDOVYVZVXZNNJNYZGJPXPMVKJNADHVKMKMDVQDYVZHEPGCJYZVJNVIJNYZXDYDPOJMIVMNZKDIOJMVKZIVNZHDINDNODIYJVIOZNYDNNJIJOMVWVGCJZIVZQVIBZGDUVXVJXCZBJPVAMZLPZIOVMYPMVIOZPHVIJJNZHDIVMDJYZOZJGJBDVIZNNZKZMDJYJHJMJPZHCVDVGJIYMZNMVHNBVOZVHNOZMYVHZWJMDIVBZIVWZGBDXVVOZMZNJGQZMNZBPDMVXVMMZDMVVMODNODXVZHZHPYVMNZKVMVKVMDNVXJGCDYJKJMNZPDMHVJOCZJLPZZMVPHIZBJXDVYJMYZVMOZYZKJPXVQDNDWDGDYVYZVKZNVMYZKJWMZNZHKMZDIXZIODQJPZVEPYJPADIVIXZDMVHZIOZNZPDMHVJHVDNQZGCJZHKVMDNAJDVKMZNZIOVYJVJDHKMZNNDJIDNHJHJQDHZIOJYJLPVGNJAMZPBMVIYZDIAGPZIXDVOVHWZHVYHDMVQVHPDOJVNBMVQPMVNEVKJIZNVNZNKZXDVGHZIOZLPVIOJVJXJGJMDYJVDIYVIVAMVIVXJIQDQZPXJHZYBVMYZBVNBZJMBZNNZPMVOCZIMDYZOJPGJPNZGVPOMZXKVPGNDBIVXZHDGZWZMIVMYZKVPGBVPBPDIMZXZWZIYJBMVIYZDIAGPZIXDVYZNNZNVMODNOVNYJDNVIJNHVDNOVMYZZHKVMOZKVMVJNPGYVAMVIVZHVMGZNZMZOJHVJOMVWVGCJYZAJMHVAZMQJMJNVIZNNZHZNHJKZMDJYJBVPBPDIMZNJGQZEPIOVMNZVJVHDBJVXJIQDQZIXDVZIOMZJNYJDNAJDYZNVNOMJNVVKZNVMYVNXJINOVIOZNWMDBVNAJMVHYJDNHZNZNYZOMVWVGCJDIOZINJVOZLPZIJVPBZYZPHVYDNXPNNVJQVIBJBCGCZVHZVVXJHPHVIVQVGCVBVPBPDIQJGOVKVMVKVMDNZQVIBJBCVMMZKZIYDYJXJMOVVKMJKMDVJMZGCVIPHVVXZNNJYZVBMZNNDQDYVYZVKJNZNNZZKDNJYDJZDIOZMIVYJIJCJNKDOVGYVXDYVYZVKVMODMYVDNPVNXMDNZNXJHZVMDVHVNZDIOZINDADXVMAJDYDVBIJNODXVYJXJHYZKMZNNVJDIOZMIJPNZQJGPIOVMDVHZIOZIPHNVIVOJMDJIVXDYVYZQDUDICVXJHVNXMDNZNHVDNXJIOMJGVYVNQJGOVVNVODQDYVYZNDINKDMVYJKZGVKVDNVBZHGJXVGXCZBVIYJVKDIOVMPHLPVYMJKJMYDVNZPNOMVJNZQJGPDMVHYZKZLPZIVNKDIXZGVYVNKVMVKDIXZGVYVNZNKDMVDNZXPMQVNYZDSJPVXGDIDXVZHHVDJYZZKVMODPKVMVVPQZMNKZMOJYZKVMDNZXJINZLPZIOZHZIOZKZMOJYJDMHVJOCZJKDIOVQVMZBPGVMHZIOZZZNOVQVZHKGZIVVODQDYVYZXMDVODQVZIXJMVEVYJKJMXVHDGGZKDNNVMMJXJHZJPVAMZLPZIOVMVNXJINPGOVNYJYMKVPGBVXCZOBVXCZOAJDVDINKDMVXVJKVMVPHVYVNJWMVNHVDNAVHJNVNYZQVIBJBCMZOMVOJYJYJPOJMBVXCZOXJIOPYJVNXMDNZNXJIODIPVQVHZZHYZEPGCJYZJVMODNOVNVDKVMVPHKVNNZDJIJXVHKJXVMMZBVIYJXJINDBJPHMZQJGQZMKVMVVODMVMIVNBMVGCVNVXVWVYVIYJIPHODMJIJKMJKMDJKZDOJPHVKJNNQZGMVUVJKVMVQVIBJBCOZMOJHVYJZNNVVODOPYZKJYZOZMNDYJJYZNZEJYZYZDSVMYZNZMPHVKMZJXPKVXVJKVMVJDMHVJLPZVGZHYZNPNOZIOVGJNPNOZIOVQVVZNKJNVZVHZVKNJJXJMMDYJVDIYVOZQZAJMVNKVMVQJGOVMKVMVXVNVJIYZHJMMZPYJDNYDVNYZKJDNIJNWMVJNYJDMHVJOCZJVJNVIJNYZDYVYZYZKJDNYVHJMOZYJDMHVJOCZJXVDZHKMJAPIYVYZKMZNNVJZHJMMZNZDNHZNNZNYZKJDNYZDSVIYJVZNKJNVZPHADGCJXCVHVYJQDIXZIOZHWJMVYZNZICVNNZYZNYZXMDVIVXJHZXJPVKDIOVMMZGVODQVHZIOZOVMYZIJZIOVIOJNJHVHVDNYZOZGVNZIOMZNPVNKDIOPMVNHVDNXJICZXDYVNZNOVJJNXJHZYJMZNYZWVOVOVNXVQZDMVXJHXDBVMMJVXZNNJVKJIOZYZWVDSJYZXCPQVIVOPMZUVHJMOVXJHVWNDIOJVDOVGDVIVVQDICVZIXVMIVYVVXVNVVHVMZGVMZOMVOJYJYMBVXCZOBDMVNNJDNQDNOVYZVMGZNXJHGDMDJNIJDOZZNOMZGVYV'
texto_cifrado = texto_cifrado.lower()


alfabeto = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

def ContaLetras(texto):
    quantidade = []
    for c in alfabeto:
        total = texto.count(c)
        quantidade.append(total)
    return quantidade


def Porcentagem(quantidade):
    porcentagem = []
    for c in quantidade:
        total = (c/len(texto_cifrado))
        porcentagem.append(total)
    return porcentagem

porcentagens = (Porcentagem(ContaLetras(texto_cifrado)))

frequencia_m = [14.634, 1.043, 3.882, 4.992, 12.570, 1.023, 1.303, 0.781, 6.186, 0.397, 0.015, 2.779, 4.738, 4.446, 9.735, 2.523, 1.204, 6.530, 6.805, 4.336, 3.639, 1.575, 0.037, 0.253, 0.006, 0.470]
frequencia = [a/100 for a in frequencia_m]
IBRA = 0.073

valores_i = []
k = 0
valor = 0
while k < 26:
    i = 0
    for n in range(26):
        valor = frequencia[n] * porcentagens[(n+k)%26]
        i += valor
    valores_i.append(i)
    k +=1


diferenças = [abs(a-IBRA) for a in valores_i]
menor_valor = min(diferenças)
chave_correta = diferenças.index(menor_valor)
print(chave_correta)